// @flow

import { keyMirror } from '../utils';

export default keyMirror([
    'ORDER_GENRES_REQUEST',
    'ORDER_GENRES_SUCCESS',
    'ORDER_GENRES_FAILURE',
    'ORDER_TEMPLATES_REQUEST',
    'ORDER_TEMPLATES_SUCCESS',
    'ORDER_TEMPLATES_FAILURE',
    'ORDER_PACK_SIZES_REQUEST',
    'ORDER_PACK_SIZES_SUCCESS',
    'ORDER_PACK_SIZES_FAILURE',
    'ORDER_EXAMPLE_REQUEST',
    'ORDER_EXAMPLE_SUCCESS',
    'ORDER_EXAMPLE_FAILURE',
]);
