// @flow

import { keyMirror } from '../utils';

export default keyMirror([
    'PROFILE_LOGIN_REQUEST',
    'PROFILE_LOGIN_SUCCESS',
    'PROFILE_LOGIN_FAILURE',
    'PROFILE_REGISTRATION_REQUEST',
    'PROFILE_REGISTRATION_SUCCESS',
    'PROFILE_REGISTRATION_FAILURE',
    'PROFILE_SET_TOKEN',
    'PROFILE_CLEAR_TOKEN',
    'PROFILE_GET_USER_REQUEST',
    'PROFILE_GET_USER_SUCCESS',
    'PROFILE_GET_USER_FAILURE',
]);
